cenit:
  environment:
    - DB_PORT=mongodb
    - RABBITMQ_BIGWIG_TX_URL=amqp://cenit_rabbit:cenit_rabbit@rabbitmq/cenit_rabbit_vhost
  build: .
  command: /usr/bin/mongod
  command: rails server -p 3000 -b '0.0.0.0'
  ports:
    - "3000:3000"
  links:
    - mongodb
    - rabbitmq

rabbitmq:
  image: rabbitmq
  environment:
      RABBITMQ_DEFAULT_PASS: cenit_rabbit
      RABBITMQ_DEFAULT_USER: cenit_rabbit
      RABBITMQ_DEFAULT_VHOST: cenit_rabbit_vhost

mongodb:
  image: mongo:3.0.2
